services:
    sherlockode_configuration.field.text:
        class: Sherlockode\ConfigurationBundle\FieldType\TextField
        tags:
            - {name: sherlockode_configuration.field }
    sherlockode_configuration.field.textarea:
        class: Sherlockode\ConfigurationBundle\FieldType\TextareaField
        tags:
            - {name: sherlockode_configuration.field }
    sherlockode_configuration.field.url:
        class: Sherlockode\ConfigurationBundle\FieldType\UrlField
        tags:
            - {name: sherlockode_configuration.field }
    sherlockode_configuration.field.datetime:
        class: Sherlockode\ConfigurationBundle\FieldType\DateTimeField
        tags:
            - {name: sherlockode_configuration.field }
    sherlockode_configuration.field.choice:
        class: Sherlockode\ConfigurationBundle\FieldType\ChoiceField
        tags:
            - {name: sherlockode_configuration.field }
    sherlockode_configuration.field.entity:
        class: Sherlockode\ConfigurationBundle\FieldType\EntityField
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - {name: sherlockode_configuration.field }
