services:
    sherlockode_configuration.field.simple:
        class: Sherlockode\ConfigurationBundle\FieldType\SimpleField
        tags:
            - {name: sherlockode_configuration.field }
    sherlockode_configuration.field.datetime:
        class: Sherlockode\ConfigurationBundle\FieldType\DateTimeField
        tags:
            - {name: sherlockode_configuration.field }
    sherlockode_configuration.field.choice:
        class: Sherlockode\ConfigurationBundle\FieldType\ChoiceField
        tags:
            - {name: sherlockode_configuration.field }
    sherlockode_configuration.field.checkbox:
        class: Sherlockode\ConfigurationBundle\FieldType\CheckboxField
        tags:
            - {name: sherlockode_configuration.field }
    sherlockode_configuration.field.entity:
        class: Sherlockode\ConfigurationBundle\FieldType\EntityField
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - {name: sherlockode_configuration.field }
